version: 0.2
env:
    variables:
        S3_BUCKET: "demo-vehicles-frontend"
phases:
    install:
        runtime-versions:
            nodejs: 16
    pre-build:
        commands:
            - echo Installing source NPM dependencies...
            - npm install --legacy-peer-deps
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started 
            - ng build --configuration production --aot
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes