version: 0.3
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "demo-vehicles-frontend"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --configuration development --aot
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes