version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "demo-vehicles-frontend"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
  post_build:
     commands:
      - aws s3 cp ./dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes